dist: bionic

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - setup=basic
    - setup=stable

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true
before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
